### ISSUE TITLE
ReferenceError: emitted is not defined

### ISSUE THREAD

**Issue by rizaldywirawan** [STECHOQ/chafon-ru5300#1]
Hallo, 

Thank  you in advance for creating this package.

I tried to use the library but got this error when use node index.js script.

![image](https://user-images.githubusercontent.com/31938164/155838532-c889d508-69d0-46d5-9dd0-79d1fda03137.png)

Can you help me to fix this?

Thank you

**Comment by iqrok** [comment]
c42b9506ee9dacb2243260b779453bc16f3cd748 should fix this error, let me know if error still happens

**Comment by rizaldywirawan** [comment]
Yep, this one works great.

One more question, can we use USB instead of network?

Thank you

**Comment by iqrok** [comment]
Currently, this lib only support network. the next step, we'll be trying to add serial RS232 support. As for USB, we still need to get some more info on how the reader works.

we only recently work on this project, so the feature is limited and bugs tend to happen.
